[package]
name = "spider_utils"
version = "2.2.13"
authors = [
    "j-mendez <jeff@a11ywatch.com>"
]
description = "Utilities to use for Spider Web Crawler."
repository = "https://github.com/spider-rs/spider"
readme = "README.md"
keywords = ["crawler", "spider"]
categories = ["web-programming", "command-line-utilities"]
license = "MIT"
documentation = "https://docs.rs/spider"
edition = "2018"

[dependencies]
indexmap = { version = "1", optional = true }

[dependencies.spider]
version = "2.0.12"
path = "../spider"

[features]
default = []
indexset = ["indexmap"]
serde = ["indexmap/serde", "spider/serde"]