[package]
name = "spider"
version = "2.2.7"
authors = [
    "j-mendez <jeff@a11ywatch.com>"
]
description = "The fastest web crawler written in Rust."
repository = "https://github.com/spider-rs/spider"
readme = "README.md"
keywords = ["crawler", "spider"]
categories = ["web-programming", "command-line-utilities"]
license = "MIT"
documentation = "https://docs.rs/spider"
edition = "2018"

[badges]
maintenance = { status = "as-is" }

[dependencies]
url = "2"
tokio-stream = "0.1"
hashbrown = { version = "0.14", default-features = true }
log = "0.4"
percent-encoding = "2.3.1"
regex = { version = "1", optional = true }
ua_generator = { version = "^0.5", optional = true }
string_concat = "0.0.1"
lazy_static = "1.4.0"
fast_html5ever = "0.26.6"
selectors = "0.25.0"
tendril = "0.4.3"
ahash = { version = "0.8", default-features = false, features = ["std"] }
cssparser = "0.31.2"
smallvec = "1"
ego-tree = "0.6.2"
num_cpus = "1.16.0"
bytes = { version = "1", features = ["serde"] }
serde = { version = "1", optional = true, features = ["derive"] }
flexbuffers = { version = "2", optional = true }
itertools = { version = "0.12.0", optional = true }
case_insensitive_string = { version = "0.2", features = ["compact", "serde"] }
chromiumoxide = { version = "0.7.0", optional = true, features = [
    "tokio-runtime",
    "bytes",
], default-features = false }
sitemap = { version = "0.4.1", optional = true }
chrono = { version = "0.4", optional = true }
cron = { version = "0.12.0", optional = true }
async-trait = { version = "0.1.75", optional = true }
strum = { version = "0.26.2", features = ["derive"] }
async_job = { version = "0.1.4", optional = true }
reqwest-middleware = { version = "0.3", optional = true }
http-cache-reqwest = { version = "0.14.0", optional = true }
const_format = { version = "0.2", optional = true }
async-openai = { version = "0.23", optional = true }
tiktoken-rs = { version = "0.5", optional = true }
lol_html = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
quick-xml = { version = "0.36.0", features = ["serde", "serialize", "async-tokio"]}
moka = { version = "0.12.8", features = ["future"], optional = true }
fastrand = { version = "2", optional = true }
http-cache-semantics = { version = "2", optional = true }
http-cache = { version = "0.19.0", optional = true, default-features = false }
http = { version = "1", optional = true }
adblock = { version = "0.8", optional = true, default-features = false, features = ["embedded-domain-resolver", "full-regex-handling"] }
phf = "0.11"
phf_codegen = "0.11"
auto_encoder = { version = "0.1", optional = true }
hyper = { version = "*", features = ["full"], optional = true}
hyper-rustls = { version = "*", optional = true }

[target.'cfg(all(not(windows), not(target_os = "android"), not(target_env = "musl")))'.dependencies]
tikv-jemallocator = { version = "0.5.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", default-features = false, features = [
    "macros",
    "time",
    "parking_lot", 
    "rt-multi-thread"
] }
fastrand = { version = "2", optional = true }
reqwest = { version = "0.12", default-features = false, features = [
    "brotli",
    "gzip",
    "deflate",
    "zstd",
    "stream",
    "http2",
    "rustls-tls",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", default-features = false, features = [
    "macros",
    "time",
    "rt"
] }
fastrand = { version = "2", optional = true, features = ["js"] }
reqwest = { version = "0.12", default-features = false, features = [
    "brotli",
    "gzip",
    "deflate",
    "stream",
    "http2",
    "rustls-tls",
] }

[features]
default = ["sync", "reqwest_native_tls_alpn", "cookies", "ua_generator", "encoding"]
regex = ["dep:regex"]
glob = ["dep:regex", "dep:itertools"]
ua_generator = ["dep:ua_generator"]
jemalloc = ["tikv-jemallocator"]
decentralized = ["serde", "flexbuffers"]
control = []
time = []
adblock = ["dep:adblock"]
sync = ["tokio/sync"]
flexbuffers = ["dep:flexbuffers"]
serde = ["dep:serde", "hashbrown/serde"]
fs = ["tokio/fs"]
full_resources = []
socks = ["reqwest/socks"]
reqwest_json = ["reqwest/json"]
sitemap = ["dep:sitemap"]
cache = ["dep:reqwest-middleware", "dep:http-cache-reqwest"]
cache_mem = ["cache", "http-cache-reqwest/manager-moka"]
cache_openai = ["dep:moka"]
cache_chrome_hybrid = ["cache", "chrome", "dep:http-cache-semantics", "dep:http-cache", "dep:http"]
chrome = ["dep:chromiumoxide"]
chrome_headed = ["chrome"]
chrome_cpu = ["chrome"]
chrome_stealth = ["chrome"]
chrome_screenshot = ["chrome"]
chrome_store_page = ["chrome", "serde"]
chrome_intercept = ["chrome"]
chrome_headless_new = ["chrome"]
cookies = ["reqwest/cookies"]
cron = ["dep:async_job", "dep:chrono", "dep:cron", "dep:async-trait"]
smart = ["chrome", "dep:regex"]
encoding = ["dep:auto_encoder"]
headers = []
real_browser = []
openai = ["chrome", "serde", "chrome_intercept", "dep:async-openai", "dep:tiktoken-rs", "dep:lol_html", "dep:serde_json"]
openai_slim_fit = []
decentralized_headers = ["dep:const_format", "dep:itertools"]
spoof = ["dep:fastrand"]
reqwest_rustls_tls = ["reqwest/rustls-tls", "hyper-rustls", "hyper"]
reqwest_native_tls = ["reqwest/native-tls"]
reqwest_native_tls_alpn = ["reqwest/native-tls-alpn"]
reqwest_native_tls_vendored = ["reqwest/native-tls-vendored"]
reqwest_native_tls_manual_roots = ["reqwest/rustls-tls-manual-roots"]
reqwest_native_tls_webpki_roots = ["reqwest/rustls-tls-webpki-roots"]
reqwest_native_tls_native_roots = ["reqwest/rustls-tls-native-roots"]
reqwest_history_dns = ["reqwest/hickory-dns"]
reqwest_multipart = ["reqwest/multipart"]
cowboy = []
tokio_io_std = ["tokio/io-std"]

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
